### ISSUE TITLE
NPM Install not working

### ISSUE THREAD

**Issue by TannerPlauche** [koenoe/cocoen#19]
I ran the `npm install --save cocoen` and received the following error message: 
`npm ERR! 404  'requestAnimationFrame' is not in the npm registry.` It seems that the NPM package has moved from camel-casing its name to all lower-case.

**Comment by poci-hu** [comment]
Until this pull request is merged, I have a hotfixed version:

https://bitbucket.org/hacky-dev/cocoen

Feel free to use it as source for npm i
(npm i https://bitbucket.org/hacky-dev/cocoen.git)

**Comment by koenoe** [comment]
@TannerPlauche thanks!
