### ISSUE TITLE
Step by Step Process

### ISSUE THREAD

**Issue by campbema** [koenoe/cocoen#30]
Hi Koenoe,

I want to use this code for a project as a banner ad example (on squarespace) but I don't know the first thing about code. Is there any way you could send me a tutorial or video on how I should go about this?

Thanks!

**Comment by koenoe** [comment]
I'd like to help you, but that's a bit hard when you don't know a thing about coding. I'd suggest to ask someone, who understands code, helping you implement this package. If that person encounters any problems I'm happy to assist.
