### ISSUE TITLE
Touch Events not Working

### ISSUE THREAD

**Issue by 0Neji** [koenoe/cocoen#31]
Hi,

I'm currently in the process of setting up my site to make use of this plugin, pretty much all is going great but dragging on touch isn't working for me. If I tap the image, the slider jumps across but I can't grab the slider and drag it across on mobile (works fine on desktop).

I'm getting the following error when trying:

    Uncaught TypeError: Cannot read property 'touches' of undefined

This is the same on your demo (https://koenromers.com/cocoen/demo.html) but does work fine on another demo that I found (http://web.uvic.ca/~wanthony/etc/ImageSlider-Cocoen.htm).

What am I missing?

Thanks,

Ben

**Comment by koenoe** [comment]
Hi Ben,

The other demo you found is v1. There has been a complete rewrite of the plugin which is being used by the current demo.

May I ask what browser and OS you're using? You could check this for example on: http://supportdetails.com/

**Comment by 0Neji** [comment]
Hi @koenoe,

I'm using Chrome 58.0.3029.110 on Windows 10. I've also tried using Chrome on my mobile device - Google Pixel with seemingly the same result (although I haven't inspected this).

Thanks for the quick response!

Ben

**Comment by koenoe** [comment]
Ok, I'll test it somewhere this week and I'll try to reproduce.
It works on my iPhone (also in chrome) and several other android devices. What android version are you using on your google pixel?

**Comment by 0Neji** [comment]
Sorry, I didn't see this - the version is 58.0.3029.83. Android 7.1.2

**Comment by koenoe** [comment]
I've reproduced the bug. I'll fix it as soon as possible, thanks for your report.

**Comment by mikhail-karan** [comment]
Hey I've managed to fix the bug by just replacing all the
` e.originalEvent.touches[0].pageX` with `e.touches[0].pageX
`
Tested it for a bit with both touch and mouse and works fine.

**Comment by Paddy-Hamilton** [comment]
@mikhail-karan  thanks for this fix, it worked for me as well

**Comment by koenoe** [comment]
It's fixed in the new release guys. Thanks @mikhail-karan
