### ISSUE TITLE
Possible to animate?

### ISSUE THREAD

**Issue by OneSprague** [koenoe/cocoen#36]
Hi,

Is it be possible to call a function that animates the slider?

Id ultimately like to be able to tell it to animate from 50% to 55% to 45% to 50% again - that way it would make it look like a wiggle and thus attract a users attention.

Thanks!

**Comment by OneSprague** [comment]
I did find a way to do this using jquery:
$(".cocoen-drag").animate({left: '53%'},400).delay(1).animate({left: '47%'},500).delay(1).animate({left: '50%'},200);
$(".cocoen div:first-child").animate({width: '53%'},400).delay(1).animate({width: '47%'},500).delay(1).animate({width: '50%'},200);

manipulating both the .cocoen-drag left  and the  .cocoen first child width  works.

**Comment by koenoe** [comment]
Good idea! How I think it should work is that you call a method with a percentage and then Cocoen will slide to that position. I'll put it on the to-do list, thanks for your help!

**Comment by pmohan6** [comment]
+1. Plus it'd be great if the animation occurs when the slider comes into view.
