### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by ruffiem** [koenoe/cocoen#37]
Just wanted to share.

https://gist.github.com/ruffiem/2a62243ffbe1e0b78a6d1afa6b240a99

**Comment by koenoe** [comment]
@ruffiem Thanks for sharing! Looks good. Although, would it be possible to import Cocoen and use the methods you need instead of duplicating them? Otherwise I need to maintain two code bases.

**Comment by ruffiem** [comment]
Sure, we can do that too ^^
Le lun. 21 août 2017 à 10:49, Koen Romers <notifications@github.com> a
écrit :
