### ISSUE TITLE
Allow slides to reveal text divs

### ISSUE THREAD

**Issue by LoneRegister** [koenoe/cocoen#38]
Currently, 
I am able to place a div on the right side, that is overwritten by the slider as you drag it right.
However, this is not possible on the left side when using standard z-index methods.

Would it be possible to update this to allow revelation of text boxes on the left, and on the right based on the position of the slider.

Temporary work around, that is not SEO friendly, is to, of course, place the text into the image itself.  However, for content reasons and SEO benefits along with anchor links and such, having actual HTML that is obscured by the left/right drag would be beneficial.

**Comment by koenoe** [comment]
@LoneRegister Can you make a JSFiddle or a Codepen so I have a better image of what you mean exactly?

**Comment by koenoe** [comment]
@LoneRegister Haha yes I meant a better understanding/image. I understand what you mean though, basically just content support for Cocoen other than images.

Cocoen is focussing on image comparison, but I'll put other content support on the roadmap. Thanks for your feature request!
