### ISSUE TITLE
Feature Request: data attribute to specify starting position etc.

### ISSUE THREAD

**Issue by gouldingken** [koenoe/cocoen#40]
It would be great to be able to specify the starting position (and other settings like min/max offsets) for the slider using a data attribute on the div.

`<div class="cocoen" data-position="75%" data-right-offset="10" data-left-offset="10">`

**Comment by koenoe** [comment]
Nice one! Thanks for your feature request. I'll definitely put this high on the to-do list.

**Comment by pmohan6** [comment]
+1
