### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by falkdav** [koenoe/cocoen#43]
I have several cocoens into tabs or accordion structure. The cocoens that are "collapsed" are broken.

My idea is to call a destroy method and the recreate.

How can I do it manually? I mean revert this

```
document.querySelectorAll('.cocoen').forEach(function(element){
  new Cocoen(element);
});
```
To execute it again.

Thank you!

**Comment by koenoe** [comment]
Why can't you initialise Cocoen after initialising the tabs/accordion?
I'll need some more of your code in order to help you. At this time I don't see the added value of a destroy method.

**Comment by mikhail-karan** [comment]
I'll add my comment here. I think the issue arises when trying to initialize Cocoen while the slider are display:none. I am having a similar issue. Don't have a solution as of yet other than recreating the div in js and reapplying Cocoen to it every time.

**Comment by mikhail-karan** [comment]
The solution I have for now is just making all the div's with cocoen sliders visible (not display:none) upon load. Run the 

`document.querySelectorAll('.cocoen').forEach(function(element){
  new Cocoen(element);
});`

and then hide them. After that it works fine and yes there is a tiny blip upon load where everything is seen but it's really fast and so far thats the best I can come up with.

@koenoe if you want to try to work on a solution together let me know, we do can a skype call or something.

**Comment by koenoe** [comment]
I need to see the issue myself, before I can think of a proper solution.
Will take a look it at, but I'm quite busy at the moment.
Thanks for reporting guys!

**Comment by jrocksinabox** [comment]
This is a great little project! I've started using it too and ran into the same issue with using them in "tabs". I'm tempted to write a destroy method, which I can see being handy(maybe not for this specific case). But my solution was to create an instance of the Cocoen on tab change, store it and look for it every time to avoid instantiating twice.

**Comment by koenoe** [comment]
Can you guys check if this is still an issue with `3.0.0`?
