### ISSUE TITLE
Can't scroll on mobile

### ISSUE THREAD

**Issue by ytteroy** [koenoe/cocoen#47]
Hello! There is a problem, that mobile phone user can't slide page to up/down. But can slide to left/right. 

`this.element.addEventListener('touchmove', this.onDrag.bind(this));`

This rewrites touchmove and allows only scroll to left/right.

**Comment by bikerdave** [comment]
I also had this issue. #48 seems to solve this.

**Comment by koenoe** [comment]
This will be fixed in v3
