### ISSUE TITLE
Coordinate failure when used inside the slider

### ISSUE THREAD

**Issue by weblabio** [koenoe/cocoen#49]
Hi, if I use Cocoen inside any slider, for example Owl or TinySlider, only the first slide works.
For the rest of the slides, when dragging or clicking, the values are set to either 2% or 98%. I found that it considers the coordinates/ratio incorrect 
```js
let openRatio = (this.leftPos + (this.dragElementWidth / 2)) - this.elementOffsetLeft;
```
Next I found a question and solution on SO:
https://stackoverflow.com/questions/50154738/cocoen-slider-in-bootstrap-carousel

I added _this.dimensions ();_ in functions: **onDragStart**() and **onTap**()
It really solved the problem.

I think this should be included in the library, because there is no way to override methods, so I had to fix the source code.

What do you think about this topic? What is the best way to use it? I would suggest or always recalculate the coordinates or add an option to enable/disable this feature.

**Comment by koenoe** [comment]
I'll be doing a full rewrite of the library soon and then I'll see what I can do about this issue :-)

**Comment by alonsoct00** [comment]
I have the same problem in the slickcarousel, when slides to a new element the drag behavior doesn't work.

**Comment by koenoe** [comment]
Better late than never, but I'm currently doing a full rewrite. What would be expected behaviour of Cocoen inside a carousel/slider?

**Comment by koenoe** [comment]
@weblabio can you try with version 3.0.0?

**Comment by jonthinkzap** [comment]
Hey, this still doesn't seem to be working as expected.

I have it setup with a bootstrap carousel here https://zapdev.29studiosdev.com/services/3d-animation/, first slide works fine, anything after that gets rendered, but not draggable.
