### ISSUE TITLE
Cocoen works fine offline, but needs F5 refresh to load left image when uploaded online

### ISSUE THREAD

**Issue by neilwhitedesign** [koenoe/cocoen#53]
Hello

I'm wanting to use multiple instances of Cocoen on my website as it's a great way to illustrate my skills in Digital Imaging and Photo Restoration.

The slider was working fine while building and testing the site offline, but for the left image to appear and the slider to move when online, an F5 refresh is required:

[](http://neilwhitedesign.co.uk/digitalimaging.html)

Has anyone experienced this same issue?
If so, can you offer advice on how to overcome this?

Any help would be much appreciated.

Thanks

**Comment by allanmferreira** [comment]
I have the same issue.

**Comment by frankie-tech** [comment]
Do you have a url or something where it is up? I can try and help

**Comment by allanmferreira** [comment]
> Do you have a url or something where it is up? I can try and help

Here
https://evandrorocha.ulisite.com/test

**Comment by neilwhitedesign** [comment]
Hello Allan

I never received a response from the creator of Cocoen, so had to research a solution for myself.

The one I found that worked was to add a script to reload the page after it had initially loaded:

<script>
window.onload = function() {
if(!window.location.hash) {
window.location = window.location + '#loaded';
window.location.reload();
}



}
</script>


I hope this helps

Regards

Neil White

[cid:a426f1cd-b5d2-4a19-9e4e-b4b2dcbffa31]<http://www.neilwhitedesign.co.uk>
Automotive    Product    Graphic    Website    Digital Imaging

________________________________

**Comment by frankie-tech** [comment]
@allanmferreira That is weird. I'm looking through the minified JS on your site, and it looks like you don't have the Cocoen init code wrapped in a event listener for when the DOM is ready.

I deleted the Cocoen generated code from the inspector, and created a new Cocoen in the console and it works fine. I _think_ the Cocoen code is running before the browser is properly sizing the image, hence the need to hard-refresh.

Try replacing your init code with this:

```js
// DOMContentLoaded is close to $().ready() in jQuery
document.addEventListener('DOMContentLoaded', function(event) {
	const beforeAfterSlider = new Cocoen(document.querySelector('.cocoen'));
}, { once: true });
```

Lemme know if that fixes things.

**Comment by allanmferreira** [comment]
> @allanmferreira That is weird. I'm looking through the minified JS on your site, and it looks like you don't have the Cocoen init code wrapped in a event listener for when the DOM is ready.
> 
> I deleted the Cocoen generated code from the inspector, and created a new Cocoen in the console and it works fine. I _think_ the Cocoen code is running before the browser is properly sizing the image, hence the need to hard-refresh.
> 
> Try replacing your init code with this:
> 
> ```js
> // DOMContentLoaded is close to $().ready() in jQuery
> document.addEventListener('DOMContentLoaded', function(event) {
> 	const beforeAfterSlider = new Cocoen(document.querySelector('.cocoen'));
> }, { once: true });
> 
> // OR
> 
> window.addEventListener('load', function(event) {
> 	const beforeAfterSlider = new Cocoen(document.querySelector('.cocoen'));
> });
> ```
> 
> Lemme know if that fixes things.

Works for me, I moved the cocoen to inside a load function.
@neilwhitedesign maybe you can try to do this too
