### ISSUE TITLE
Instead of Click and Drag - Drag on Mouse Move

### ISSUE THREAD

**Issue by just-refresh** [koenoe/cocoen#77]
Drag on Mouse Movement over the element, instead of click and drag?

**Comment by koenoe** [comment]
Why?

**Comment by just-refresh** [comment]
Following the Cursor after enter the area. If there is no indicator for the user, that shows the possibility to move.

**Comment by koenoe** [comment]
I’m sorry, not a functionality I’m considering at the moment.
