### ISSUE TITLE
How Do I apply the options

### ISSUE THREAD

**Issue by oidz1234** [koenoe/cocoen#79]
For example I want to use the start="10" option. Where would I write this? I have tried every place I can think of. My code at the moment is basically the example code from the readme. 
Thanks!

**Comment by koenoe** [comment]
For now you have to pass them to the `create` method like this: `Cocoen.create(element, { start: 10 })`. It's still on my to-do list to allow setting options via data attributes that the `parse` method will apply.
Another approach could be using the Web Component directly like this: https://github.com/koenoe/cocoen/blob/main/src/components/cocoen.stories.ts#L45-L51

**Comment by oidz1234** [comment]
Thank you very much :)
