### ISSUE TITLE
Cocoen Slider doesn't work in a Bootstrap 4 Modal Popup window

### ISSUE THREAD

**Issue by muizonline** [koenoe/cocoen#81]
Wonderful Before/After Slider, and easy to install and get working on a plain page.

However, the slider doesn't seem to work when it's installed within the content of a Bootstrap 4 Modal Popup window, which is where I'd really like to use it.

I converted the demo sample page to a test page that resembles the Bootstrap layout of the page I want to use it on. I've put the before/after images in the "spotlight card", and also in the Modal Popup code section, where I really like to get it working. The slider works fine in the spotlight card. But when the Modal Popup (with the full page text rather than just the excerpt) is opened, by clicking the Read More button at the bottom of the card, it looks like it might work, ie one image and the slider are displayed, but the slider won't move.

I've zipped up the demo page and the dependent css, js, and grafix files and attached it here.

Thanks,

Muiz
[cocoenDemo.zip](https://github.com/koenoe/cocoen/files/6837089/cocoenDemo.zip)

**Comment by koenoe** [comment]
Can you create a codepen where you demonstrate the issue? Many thanks

**Comment by muizonline** [comment]
Thanks for your response, Koen.

I’ve looked at and experimented with existing codepen demos before, but I’ve never created a codepen of my own, so I needed a bit of learning to figure out how to transfer the appropriate sections of code from my demo file at my website to my codepen.

My system details: 
Mac OS Big Sur (11.4), using Firefox version 90.0.2. 

Also have tested my own demo page and my codepen in Chrome version 92.0.4515.131. The both work the same way as they do in Firefox.

In Safari version 14.1.1, viewing my demo page at my website, the problem is the same (slider works in the Bootstrap card, but not in the opened modal popup. 

But using Safari to view the codepen, the slider works in the Bootstrap card, but the screen goes all white when I open the modal window (in other words none of the modal popup content can be seen). Clicking in various places on the blank white area closes the modal popup and the Bootstrap card underneath it and be seen again — very odd.

Demo page at my website
https://visibleimpressions.com/R/pages/demos/cocoen/cocoenCodepen.php <https://visibleimpressions.com/R/pages/demos/cocoen/cocoenCodepen.php>

My codepen 
https://codepen.io/muizonline/pen/ExmJLYg <https://codepen.io/muizonline/pen/ExmJLYg>

I’m hoping that you can see right away what I’m doing wrong.

Thanks for the support.

Beat regards,

Muiz

Muiz Brinkerhoff
Santa Rosa, California, USA
***@***.***

**Comment by koenoe** [comment]
Thanks for your Codepen, this is not an issue in Cocoen.
You should initialise Cocoen after you open the Modal, by the looks of it you can use https://getbootstrap.com/docs/4.0/components/modal/#modaltoggle this in Bootstrap.

**Comment by muizonline** [comment]
Many thanks for the very quick response Koen, and for pointing out the problem was the timing of the Cocoon initialization.

The code snippet at the bottom of the Bootstrap 4 page about using the modal events (show, shown, hide, hidden) allowed me to test this:

	$(‘#modal_ID').on('shown.bs.modal', function () {
			Cocoen.create(document.querySelector(‘.cocoen'));
	})

which works.

Plus giving multiple Bootstrap cards, and their associated modal popups unique modal names and unique cocoen div class names, I’m able to have one Cocoen type before/after image in each card.

Now that is is working, what I really want to do is to have multiple images in one or more cards. I’ve already demonstrated that switching to the syntax for multiple instances:

Cocoen.parse(document.body); 

doesn’t work.

Is there a syntax to limit the parsing to only the code within a single modal, rather than parsing the entire body element/object, so that each card/modal could have it’s own multiple cocoen images?


Best Regards,

Muiz

**Comment by koenoe** [comment]
You could pass any dom element to `Cocoen.parse`. 
In your case:
```
Cocoen.parse(document.querySelectorAll('.modal'));
```

**Comment by muizonline** [comment]
========
Codepen
https://codepen.io/muizonline/pen/ExmJLYg <https://codepen.io/muizonline/pen/ExmJLYg>

And my website demo page:
https://visibleimpressions.com/R/pages/demos/cocoen/cocoenCodepen.php <https://visibleimpressions.com/R/pages/demos/cocoen/cocoenCodepen.php>

========

Thanks for the additional javascript/DOM syntax.

 Since I have 2 different modal popups, the first with a single cocoen-container, and the 2nd with 2 cocoen-containers, I'm assuming that

parse(document.querySelectorAll('.modal')); 

should parse both .modal containers, and find all 3 cocoen-containers, though I'm only interested the 2nd modal with the 2 cocoen-containers.

Tried it anyway with '.modal' in the 2nd Cocoen initialization code line

Cocoen.parse(document.querySelectorAll('.modal')); 

but it doesn't work at all. Both pairs of before and after images are shown in the modal, one above the other, like it was when I was originally intializaing Cocoen before the modal popup opened. 

In the browser Inspector Console window, I'm seeing this error:

Uncaught TypeError: n.querySelectorAll is not a function (parse.ts:5:31)
    p parse.ts:5
    <anonymous> pen.js:6
    jQuery 7
    r modal.js:260
    i jQuery
    handle util.js:32
    jQuery 7
    triggerTransitionEnd util.js:116
    t util.js:48
    setTimeout handler*t util.js:46
    _showElement modal.js:268
    show modal.js:149
    i jQuery
    handle util.js:32
    jQuery 8
    _showBackdrop modal.js:373
    show modal.js:149
    _jQueryInterface modal.js:517
    jQuery 2
    _jQueryInterface modal.js:498
    Yn modal.js:560
    jQuery 8
    <anonymous> alert.js:161
    <anonymous> bootstrap.min.js:6
    <anonymous> bootstrap.min.js:6 

—————-

Next I added .cocoen1 to the first .modal container, and .cocoen2 to the 2nd .modal so I could specify which to parse and then modified querySelectorAll from 'modal'  to '.cocoen2 .cocoen'

$('#openModal_cocoen1').on('shown.bs.modal', function () {
	Cocoen.create(document.querySelector('.cocoen1 .cocoen')); // THIS WORKS
});

$('#openModal_cocoen2').on('shown.bs.modal', function () {
	Cocoen.parse(document.querySelectorAll('.cocoen2 .cocoen')); // THIS DOESN'T
});

Whether I launch the 1st one (#openModal_cocoen1) first and then the 2nd (#openModal_cocoen2), or the 2nd one first, and then the 1st one ... only the first one with the single cocoen-container works 

And in both cases, the sane "Uncaught TypeError: n.querySelectorAll is not a function" is the error message in the Inspector Console.

Any ideas what is going on?

Thanks,

Muiz


_______________________
Muiz Brinkerhoff (he/him)
***@***.***
Santa Rosa, CA 95403
USA

**Comment by koenoe** [comment]
Ah, it needs to be one DOM element/container, like `document.body`.
Good luck!

**Comment by muizonline** [comment]
Your statement, plus a bit of additional research, and an intuitive suggestion just now and I tried this syntax

$('#openModal_cocoen2').on('shown.bs.modal', function () {
 	Cocoen.parse(document.getElementById('openModal_cocoen2'));
});

and it WORKS!!

Plus it doesn't make the 1st modal cocoen-container with just the single image stop working. The both work, multiple times.

Many thanks for your assistance.

Can I "buy" you a coffee?

Muiz
