### ISSUE TITLE
Slider is not keyboard-accessible

### ISSUE THREAD

**Issue by ThomasRettig** [koenoe/cocoen#88]
The slider does not react to <kbd>left arrow</kbd> and <kbd>right arrow</kbd> making it inaccessible for keyboard users. I suggest that an actual ```<input>``` element be used instead of the existing ```div```, or if some Javascript can be introduced to make it keyboard-accessible.

**Comment by koenoe** [comment]
Thanks for the suggestion, but this is not something I'm looking to add to Cocoen.
